name: Deploy Project

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened]
    branches: [main]

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
<<<<<<< HEAD
      - name: Deploy
        run: echo "Simulated deployment complete!"
=======

      - name: Deploy
        run: echo "Simulated deployment complete ........"
>>>>>>> parent of 0a30df4 (Run jobs sequentially with needs keyword)
